# Generated by Django 6.0.3 on 2026-04-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
