# Generated by Django 6.0.3 on 2026-04-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0002_farmer_otp_farmer_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkentry',
            name='milk_type',
            field=models.CharField(choices=[('cow', 'Cow'), ('buffalo', 'Buffalo')], default='cow', max_length=10),
        ),
    ]
