# Generated by Django 6.0.3 on 2026-04-17 06:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_app', '0003_milkentry_milk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkentry',
            name='snf',
            field=models.FloatField(default=8.5),
        ),
        migrations.CreateModel(
            name='FeedDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.CharField(default='Cattle Feed', max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk_app.farmer')),
            ],
        ),
    ]
